package com.rudra.hisab.util

class Strings(private val lang: AppLanguage) {

    private val bn get() = lang == AppLanguage.BANGLA

    fun nameOrBangla(nameEn: String, nameBn: String) = if (bn) nameBn else nameEn

    // ── General ──
    val ok get() = if (bn) "ঠিক" else "OK"
    val cancel get() = if (bn) "বাতিল" else "Cancel"
    val save get() = if (bn) "সংরক্ষণ" else "Save"
    val saving get() = if (bn) "সংরক্ষণ..." else "Saving..."
    val add get() = if (bn) "যোগ করুন" else "Add"
    val delete get() = if (bn) "মুছুন" else "Delete"
    val close get() = if (bn) "বন্ধ" else "Close"
    val confirm get() = if (bn) "নিশ্চিত" else "Confirm"
    val change get() = if (bn) "পরিবর্তন" else "Change"
    val loading get() = if (bn) "লোড হচ্ছে..." else "Loading..."
    val apply get() = if (bn) "প্রয়োগ" else "Apply"
    val undo get() = if (bn) "পূর্বাবস্থায় আনুন" else "Undo"
    val on get() = if (bn) "চালু" else "On"
    val off get() = if (bn) "বন্ধ" else "Off"
    val next get() = if (bn) "পরবর্তী" else "Next"
    val export get() = if (bn) "এক্সপোর্ট" else "Export"
    val exporting get() = if (bn) "এক্সপোর্ট হচ্ছে..." else "Exporting..."
    val import_ get() = if (bn) "ইম্পোর্ট" else "Import"

    // ── Navigation ──
    val navDashboard get() = if (bn) "ড্যাশবোর্ড" else "Dashboard"
    val navStock get() = if (bn) "মজুদ" else "Stock"
    val navSale get() = if (bn) "বিক্রয়" else "Sale"
    val navCustomers get() = if (bn) "গ্রাহক" else "Customers"
    val navMore get() = if (bn) "আরও" else "More"

    // ── Dashboard ──
    val dashboardTitle get() = if (bn) "ড্যাশবোর্ড" else "Dashboard"
    val todaysSales get() = if (bn) "আজকের বিক্রয়" else "Today's Sales"
    val netProfit get() = if (bn) "নিট মুনাফা" else "Net Profit"
    val todaysExpenses get() = if (bn) "আজকের খরচ" else "Today's Expenses"
    val totalDues get() = if (bn) "মোট বাকি" else "Total Dues"
    val todayBreakdown get() = if (bn) "আজকের হিসাব" else "Today's Breakdown"
    val monthlyBreakdown get() = if (bn) "মাসিক হিসাব" else "Monthly Breakdown"
    val todayRevenue get() = if (bn) "আজকের বিক্রয়" else "Today's Revenue"
    val monthRevenue get() = if (bn) "এই মাসের বিক্রয়" else "This Month's Revenue"
    val sales get() = if (bn) "বিক্রয়" else "Sales"
    val thisMonth get() = if (bn) "এই মাস" else "This Month"
    val ofMonth get() = if (bn) "মাসের" else "of month"
    val quickStats get() = if (bn) "দ্রুত পরিসংখ্যান" else "Quick Stats"
    val saleCount get() = if (bn) "বিক্রয় সংখ্যা" else "Sale Count"
    val purchases get() = if (bn) "ক্রয় (আজ)" else "Purchases"
    val purchasesShort get() = if (bn) "ক্রয়" else "Purchase"
    val creditGiven get() = if (bn) "ক্রেডিট" else "Credit Given"
    val products get() = if (bn) "পণ্য" else "Products"
    val customers get() = if (bn) "গ্রাহক" else "Customers"
    val stockOverview get() = if (bn) "স্টক ওভারভিউ" else "Stock Overview"
    val quickActions get() = if (bn) "দ্রুত অ্যাকশন" else "Quick Actions"
    val qaSale get() = if (bn) "বিক্রয়" else "Sale"
    val qaExpense get() = if (bn) "খরচ" else "Expense"
    val qaStock get() = if (bn) "স্টক" else "Stock"
    val qaPayment get() = if (bn) "পেমেন্ট" else "Payment"
    val qaPurchase get() = if (bn) "ক্রয়" else "Purchase"
    val inventorySummary get() = if (bn) "ইনভেন্টরি সারাংশ" else "Inventory Summary"
    val totalProducts get() = if (bn) "মোট পণ্য" else "Total Products"
    val stockValue get() = if (bn) "স্টক মূল্য" else "Stock Value"
    val lowStock get() = if (bn) "কম স্টক" else "Low Stock"
    val stockHealth get() = if (bn) "স্টক হেলথ" else "Stock Health"
    val good get() = if (bn) "ভাল" else "Good"
    val quickSale get() = if (bn) "দ্রুত বিক্রয়" else "Quick Sale"
    val quickExpense get() = if (bn) "দ্রুত খরচ" else "Quick Expense"
    val quickStock get() = if (bn) "দ্রুত স্টক" else "Quick Stock"
    val quickPayment get() = if (bn) "দ্রুত পেমেন্ট" else "Quick Payment"
    val searchProducts get() = if (bn) "পণ্য খুঁজুন..." else "Search products..."
    val searchCustomers get() = if (bn) "গ্রাহক খুঁজুন..." else "Search customers..."
    val quantity get() = if (bn) "পরিমাণ" else "Quantity"
    val total get() = if (bn) "মোট" else "Total"
    val paymentType get() = if (bn) "পরিশোধের ধরন" else "Payment Type"
    val cash get() = if (bn) "নগদ" else "Cash"
    val credit get() = if (bn) "বাকি" else "Credit"
    val partial get() = if (bn) "আংশিক" else "Partial"
    val paidAmount get() = if (bn) "প্রাপ্ত পরিমাণ" else "Paid Amount"
    val receivedAmount get() = if (bn) "প্রাপ্ত টাকা" else "Received Amount"
    val saleSuccessful get() = if (bn) "বিক্রয় সফল!" else "Sale successful!"
    val saleComplete get() = if (bn) "বিক্রয় সফল!" else "Sale Complete!"
    val processing get() = if (bn) "হিসাব করা হচ্ছে..." else "Processing..."
    val notes get() = if (bn) "নোট" else "Note"
    val description get() = if (bn) "বিবরণ" else "Description"
    val stockIn get() = if (bn) "স্টক ইন" else "Stock In"
    val stockOut get() = if (bn) "স্টক আউট" else "Stock Out"
    val receive get() = if (bn) "গ্রহণ" else "Receive"
    val pay get() = if (bn) "পে" else "Pay"
    val due get() = if (bn) "বাকি" else "Due"
    val amount get() = if (bn) "পরিমাণ" else "Amount"
    val lowStockAlertCount get() = if (bn) "টি পণ্যের স্টক কম!" else "products low on stock!"
    val tapToRestock get() = if (bn) "পুনরায় স্টক দিতে ট্যাপ করুন" else "Tap to restock"
    val quickDialogSale get() = if (bn) "বিক্রয়" else "Sale"
    val quickDialogExpense get() = if (bn) "খরচ" else "Expense"
    val quickDialogStock get() = if (bn) "স্টক" else "Stock"
    val quickDialogPayment get() = if (bn) "পেমেন্ট" else "Payment"

    // ── Sale ──
    val newSale get() = if (bn) "নতুন বিক্রয়" else "New Sale"

    val noProducts get() = if (bn) "কোনো পণ্য নেই" else "No products"
    val stockLabel get() = if (bn) "স্টক" else "Stock"
    val price get() = if (bn) "দাম" else "Price"
    val confirmSale get() = if (bn) "বিক্রয় নিশ্চিত" else "Confirm Sale"
    val confirmSaleShort get() = if (bn) "বিক্রয় নিশ্চিত করুন" else "Confirm Sale"

    // ── QuickSale ──
    val quickSaleTitle get() = if (bn) "দ্রুত বিক্রয়" else "Quick Sale"
    val cart get() = if (bn) "কার্ট" else "Cart"
    val addProductsFirst get() = if (bn) "প্রথমে পণ্য যোগ করুন" else "Add products first"
    val noProductsFound get() = if (bn) "কোনো পণ্য পাওয়া যায়নি" else "No products found"
    val history get() = if (bn) "ইতিহাস" else "History"
    val max get() = if (bn) "সর্বোচ্চ" else "Max"
    val available get() = if (bn) "বিক্রি করতে পারবেন" else "available"
    val noSalesToday get() = if (bn) "আজকের কোনো বিক্রয় নেই" else "No sales today"
    val pcs get() = if (bn) "পিস" else "pcs"
    val estProfit get() = if (bn) "সম্ভাব্য লাভ" else "Est. Profit"
    val cartTitle get() = if (bn) "কার্ট" else "Cart"
    val newCustomer get() = if (bn) "নতুন গ্রাহক" else "New Customer"
    val name get() = if (bn) "নাম" else "Name"
    val phone get() = if (bn) "ফোন" else "Phone"
    val phoneNumber get() = if (bn) "ফোন নম্বর" else "Phone"

    // ── Expense ──
    val expenses get() = if (bn) "খরচ" else "Expenses"
    val addExpense get() = if (bn) "খরচ যোগ" else "Add Expense"
    val all get() = if (bn) "সব" else "All"
    val today get() = if (bn) "আজ" else "Today"
    val week get() = if (bn) "সপ্তাহ" else "Week"
    val month get() = if (bn) "মাস" else "Month"
    val totalExpensesLabel get() = if (bn) "মোট" else "Total"
    val noExpenses get() = if (bn) "কোনো খরচ নেই" else "No expenses"
    val expenseDeleted get() = if (bn) "খরচ মুছে ফেলা হয়েছে" else "Expense deleted"
    val category get() = if (bn) "ক্যাটাগরি" else "Category"
    val transport get() = if (bn) "পরিবহন" else "Transport"
    val labor get() = if (bn) "শ্রম" else "Labor"
    val rent get() = if (bn) "ভাড়া" else "Rent"
    val utility get() = if (bn) "ইউটিলিটি" else "Utility"
    val purchase get() = if (bn) "ক্রয়" else "Purchase"
    val other get() = if (bn) "অন্যান্য" else "Other"
    val descriptionOptional get() = if (bn) "বিবরণ (ঐচ্ছিক)" else "Description (optional)"

    // ── Inventory ──
    val inventory get() = if (bn) "মজুদ" else "Inventory"
    val addProduct get() = if (bn) "পণ্য যোগ করুন" else "Add Product"
    val items get() = if (bn) "পণ্য" else "Items"
    val lowStockValue get() = if (bn) "কম স্টক" else "Low Stock"
    val deleteProduct get() = if (bn) "পণ্য মুছুন" else "Delete Product"
    val newProduct get() = if (bn) "নতুন পণ্য" else "New Product"
    val productNameEnglish get() = if (bn) "পণ্যের নাম (ইংরেজি)" else "Product Name (English)"
    val productNameBangla get() = if (bn) "পণ্যের নাম (বাংলা)" else "Product Name (Bengali)"
    val unit get() = if (bn) "একক" else "Unit"
    val productCategory get() = if (bn) "বিভাগ" else "Category"
    val buyPrice get() = if (bn) "ক্রয় মূল্য" else "Buy Price"
    val sellPrice get() = if (bn) "বিক্রয় মূল্য" else "Sell Price"
    val minStock get() = if (bn) "নিম্ন সীমা" else "Min Stock"
    val currentStock get() = if (bn) "বর্তমান স্টক" else "Current Stock"
    val reasonNote get() = if (bn) "কারণ/নোট" else "Reason/Note"
    val reasonQuestion get() = if (bn) "কেন স্টক পরিবর্তন করছেন?" else "Why are you changing stock?"
    val reasonRequired get() = if (bn) "কারণ উল্লেখ করা আবশ্যক" else "Reason is required"
    val noTransactions get() = if (bn) "কোনো লেনদেন নেই" else "No transactions"
    val qty get() = if (bn) "পরিমাণ" else "Qty"
    val buy get() = if (bn) "ক্রয়" else "Buy"
    val transactionHistory get() = if (bn) "লেনদেন ইতিহাস" else "Transaction History"
    val cannotDelete get() = if (bn) "মুছা যাবে না" else "Cannot Delete"

    // ── Customers ──
    val addCustomer get() = if (bn) "গ্রাহক যোগ" else "Add Customer"
    val customerTitle get() = if (bn) "গ্রাহক" else "Customers"
    val totalLabel get() = if (bn) "মোট" else "Total"
    val paid get() = if (bn) "পরিশোধিত" else "Paid"
    val searchCustomer get() = if (bn) "গ্রাহক খুঁজুন" else "Search customer"
    val noCustomersYet get() = if (bn) "কোনো গ্রাহক নেই — বাকি বিক্রয় গ্রাহক যোগ করবে" else "No customers yet — Credit sales will add customers"
    val noCustomersFound get() = if (bn) "কোনো গ্রাহক পাওয়া যায়নি" else "No customers found"
    val deleteCustomer get() = if (bn) "গ্রাহক মুছুন" else "Delete Customer"
    val address get() = if (bn) "ঠিকানা" else "Address"

    // ── Reports ──
    val reports get() = if (bn) "রিপোর্ট" else "Reports"
    val totalSales get() = if (bn) "মোট বিক্রয়" else "Total Sales"
    val totalExpenses get() = if (bn) "মোট খরচ" else "Total Expenses"
    val netProfitLabel get() = if (bn) "নেট লাভ" else "Net Profit"
    val salesReport get() = if (bn) "বিক্রয় রিপোর্ট" else "Sales Report"
    val totalPaid get() = if (bn) "মোট আদায়" else "Total Paid"
    val totalDue get() = if (bn) "মোট বাকি" else "Total Due"
    val salesCount get() = if (bn) "বিক্রয় সংখ্যা" else "Sales Count"
    val avgSale get() = if (bn) "গড় বিক্রয়" else "Avg Sale"
    val expenseAnalysis get() = if (bn) "খরচ বিশ্লেষণ" else "Expense Analysis"
    val profitLoss get() = if (bn) "লাভ-ক্ষতি" else "Profit & Loss"
    val totalRevenue get() = if (bn) "মোট আয়" else "Total Revenue"
    val profitMargin get() = if (bn) "মুনাফার হার" else "Profit Margin"
    val customerDues get() = if (bn) "গ্রাহক বাকি" else "Customer Dues"
    val dueCustomers get() = if (bn) "বাকি গ্রাহক" else "Due Customers"
    val stockAlerts get() = if (bn) "মজুদ সতর্কতা" else "Stock Alerts"
    val lowStockItems get() = if (bn) "কম স্টক পণ্য" else "Low Stock Items"
    val totalStockValue get() = if (bn) "মোট স্টক মূল্য" else "Total Stock Value"
    val exportReport get() = if (bn) "রিপোর্ট এক্সপোর্ট" else "Export Report"
    val exportFormatHint get() = if (bn) "CSV, Excel বা PDF ফরম্যাটে এক্সপোর্ট করুন" else "Export in CSV, Excel or PDF format"

    // ── Analytics ──
    val analyticsTitle get() = if (bn) "রিপোর্ট ও বিশ্লেষণ" else "Reports & Analytics"
    val weeklyProfit get() = if (bn) "সাপ্তাহিক মুনাফা" else "Weekly Profit"
    val customerOutstanding get() = if (bn) "গ্রাহক বকেয়া" else "Customer Outstanding"
    val productProfit30 get() = if (bn) "পণ্য লাভ (৩০ দিন)" else "Product Profit (30 days)"
    val monthlyGrowth get() = if (bn) "মাসিক প্রবৃদ্ধি" else "Monthly Growth"
    val cashFlowDaily get() = if (bn) "নগদ প্রবাহ (দৈনিক)" else "Cash Flow (Daily)"
    val topProducts get() = if (bn) "সেরা বিক্রয়" else "Top Products"
    val stockAlert get() = if (bn) "স্টক সতর্কতা" else "Stock Alert"
    val slowMovers14 get() = if (bn) "ধীরগতির পণ্য (১৪+ দিন)" else "Slow Movers (14+ days)"
    val dueAging get() = if (bn) "বাকি সময়সীমা" else "Due Aging"
    val notEnoughData get() = if (bn) "পর্যাপ্ত তথ্য নেই। আরও বিক্রয় ও খরচ যোগ করার পর এখানে বিশ্লেষণ দেখুন।" else "Not enough data. Add more sales and expenses to see analysis here."
    val generatePdf get() = if (bn) "পিডিএফ রিপোর্ট তৈরি করুন" else "Generate PDF Report"

    // ── DailyClose ──
    val dailyClose get() = if (bn) "দৈনিক সমাপ্তি" else "Daily Close"
    val dayClosedSuccess get() = if (bn) "দিন সফলভাবে বন্ধ!" else "Day closed successfully!"
    val seeYouTomorrow get() = if (bn) "আগামীকাল আবার দেখা হবে" else "See you tomorrow"
    val todayAlreadyClosed get() = if (bn) "আজকের হিসাব আগেই বন্ধ হয়েছে" else "Today already closed"
    val cashSales get() = if (bn) "নগদ বিক্রয়" else "Cash Sales"
    val creditSales get() = if (bn) "বাকি বিক্রয়" else "Credit Sales"
    val newDues get() = if (bn) "নতুন বাকি" else "New Dues"
    val paymentsReceived get() = if (bn) "পেমেন্ট পেয়েছি" else "Payments Received"
    val closing get() = if (bn) "হিসাব বন্ধ হচ্ছে..." else "Closing..."
    val closeDay get() = if (bn) "দিন বন্ধ করুন" else "Close Day"
    val last7Days get() = if (bn) "গত ৭ দিন" else "Last 7 Days"
    val salesLabel get() = if (bn) "বিক্রয়" else "Sales"
    val expensesLabel get() = if (bn) "খরচ" else "Expenses"

    // ── Accounting ──
    val accounting get() = if (bn) "হিসাবরক্ষণ" else "Accounting"
    val cashBook get() = if (bn) "নগদ বই" else "Cash Book"
    val ledger get() = if (bn) "খতিয়ান" else "Ledger"
    val todaysIn get() = if (bn) "আজকের ইন" else "Today's In"
    val todaysOut get() = if (bn) "আজকের আউট" else "Today's Out"
    val netBalance get() = if (bn) "নেট ব্যালেন্স" else "Net Balance"
    val customerLabel get() = if (bn) "গ্রাহক" else "Customer"
    val supplier get() = if (bn) "সরবরাহকারী" else "Supplier"
    val general get() = if (bn) "সাধারণ" else "General"
    val expenseComingSoon get() = if (bn) "খরচ ব্যবস্থাপনা শীঘ্রই আসছে" else "Expense management coming soon"
    val cashIn get() = if (bn) "নগদ ইন" else "Cash In"
    val cashOut get() = if (bn) "নগদ আউট" else "Cash Out"

    // ── Settings ──
    val settings get() = if (bn) "সেটিংস" else "Settings"
    val languageTheme get() = if (bn) "ভাষা ও থিম" else "Language & Theme"
    val language get() = if (bn) "ভাষা" else "Language"
    val theme get() = if (bn) "থিম" else "Theme"
    val light get() = if (bn) "হালকা" else "Light"
    val dark get() = if (bn) "গাঢ়" else "Dark"
    val system get() = if (bn) "সিস্টেম" else "System"
    val fontSize get() = if (bn) "ফন্ট সাইজ" else "Font Size"
    val small get() = if (bn) "ছোট" else "Small"
    val medium get() = if (bn) "মধ্যম" else "Medium"
    val large get() = if (bn) "বড়" else "Large"
    val shop get() = if (bn) "দোকান" else "Shop"
    val shopInfo get() = if (bn) "দোকানের তথ্য" else "Shop Info"
    val setName get() = if (bn) "নাম সেট করুন" else "Set name"
    val security get() = if (bn) "নিরাপত্তা" else "Security"
    val pin get() = if (bn) "পিন" else "PIN"
    val pinOn get() = if (bn) "পিন চালু" else "PIN On"
    val pinOff get() = if (bn) "পিন বন্ধ" else "PIN Off"
    val removePin get() = if (bn) "পিন সরান" else "Remove PIN"
    val disablePin get() = if (bn) "পিন নিষ্ক্রিয় করুন" else "Disable PIN"
    val biometricLock get() = if (bn) "বায়োমেট্রিক লক" else "Biometric Lock"
    val salesInventory get() = if (bn) "বিক্রয় ও ইনভেন্টরি" else "Sales & Inventory"
    val cartMode get() = if (bn) "কার্ট মোড" else "Cart Mode"
    val fabMode get() = if (bn) "FAB মোড" else "FAB Mode"
    val batchTracking get() = if (bn) "ব্যাচ/মেয়াদ ট্র্যাকিং" else "Batch Tracking"
    val customersTransactions get() = if (bn) "গ্রাহক ও লেনদেন" else "Customers & Transactions"
    val creditLimit get() = if (bn) "ক্রেডিট লিমিট" else "Credit Limit"
    val unlimited get() = if (bn) "সীমাহীন" else "Unlimited"
    val deleteWindow get() = if (bn) "মুছার সময়সীমা" else "Delete Window"
    val hours get() = if (bn) "ঘন্টা" else "hours"
    val notifications get() = if (bn) "নোটিফিকেশন" else "Notifications"
    val saleReminder get() = if (bn) "বিক্রয় রিমাইন্ডার সময়" else "Sale Reminder"
    val monthlyReport get() = if (bn) "মাসিক রিপোর্ট রিমাইন্ডার" else "Monthly Report"
    val navigation get() = if (bn) "নেভিগেশন" else "Navigation"
    val navOrder get() = if (bn) "নেভিগেশন অর্ডার" else "Nav Order"
    val changeMenuOrder get() = if (bn) "নিচের মেনুর অর্ডার পরিবর্তন" else "Change bottom menu order"
    val quickActionSetting get() = if (bn) "দ্রুত অ্যাকশন" else "Quick Actions"
    val dashboardButtons get() = if (bn) "ড্যাশবোর্ডে কোন বাটন দেখাবে" else "Which buttons on dashboard"
    val dataBackup get() = if (bn) "ডেটা ও ব্যাকআপ" else "Data & Backup"
    val autoBackup get() = if (bn) "অটো ব্যাকআপ" else "Auto Backup"
    val daily get() = if (bn) "প্রতিদিন" else "Daily"
    val weekly get() = if (bn) "সাপ্তাহিক" else "Weekly"
    val backupFrequency get() = if (bn) "ব্যাকআপ ফ্রিকোয়েন্সি" else "Backup Frequency"
    val backupNow get() = if (bn) "এখনই ব্যাকআপ নিন" else "Backup Now"
    val last get() = if (bn) "সর্বশেষ" else "Last"
    val neverBackedUp get() = if (bn) "কখনো ব্যাকআপ নেয়া হয়নি" else "Never backed up"
    val dataExport get() = if (bn) "ডেটা এক্সপোর্ট" else "Data Export"
    val dataImport get() = if (bn) "ডেটা ইম্পোর্ট" else "Data Import"
    val restoreFromJson get() = if (bn) "JSON ফাইল থেকে পুনরুদ্ধার" else "Restore from JSON"
    val clearAllData get() = if (bn) "সব ডেটা মুছুন" else "Clear All Data"
    val deleteAllData get() = if (bn) "সব ডেটা মুছুন" else "Delete All Data"
    val permanentlyDelete get() = if (bn) "সমস্ত তথ্য স্থায়ীভাবে মুছে ফেলুন" else "Permanently delete all data"
    val app get() = if (bn) "অ্যাপ" else "App"
    val about get() = if (bn) "সম্পর্কে" else "About"
    val pinSetup get() = if (bn) "পিন সেটআপ" else "Pin Setup"
    val oldPin get() = if (bn) "পুরনো পিন" else "Old Pin"
    val newPin get() = if (bn) "নতুন পিন" else "New Pin"
    val enterPin get() = if (bn) "পিন দিন" else "Enter PIN"
    val enterCurrentPin get() = if (bn) "বর্তমান পিন দিন" else "Enter current PIN"
    val enterNewPin get() = if (bn) "নতুন ৪-ডিজিটের পিন দিন" else "Enter new 4-digit PIN"
    val reenterPin get() = if (bn) "পিন আবার দিন" else "Re-enter PIN"
    val shopName get() = if (bn) "দোকানের নাম" else "Shop Name"
    val hourLabel get() = if (bn) "ঘন্টা" else "Hour"
    val minute get() = if (bn) "মিনিট" else "Minute"
    val selectFormat get() = if (bn) "ফরম্যাট নির্বাচন করুন:" else "Select format:"
    val pasteJson get() = if (bn) "JSON ডেটা পেস্ট করুন:" else "Paste JSON data:"
    val deleteConfirm get() = if (bn) "সমস্ত তথ্য স্থায়ীভাবে মুছে যাবে! এই কাজ পূর্বাবস্থায় ফেরানো যাবে না। আপনি কি নিশ্চিত?" else "All data will be permanently deleted! This action cannot be undone. Are you sure?"

    // ── Dynamic strings (methods) ──
    fun saleCountNum(count: Int) = if (bn) "$count টি" else "$count"
    fun dueCustomerCount(count: Int) = if (bn) "$count জন" else "$count"
    fun dayName(index: Int): String = if (bn) when (index) {
        0 -> "শনি"; 1 -> "রবি"; 2 -> "সোম"; 3 -> "মঙ্গল"; 4 -> "বুধ"
        5 -> "বৃহস্পতি"; 6 -> "শুক্র"; else -> "দিন $index"
    } else when (index) {
        0 -> "Sat"; 1 -> "Sun"; 2 -> "Mon"; 3 -> "Tue"; 4 -> "Wed"
        5 -> "Thu"; 6 -> "Fri"; else -> "Day $index"
    }
    fun dueAgingLabel(bracket: String): String = if (bn) when (bracket) {
        "0-7 days" -> "০-৭ দিন"; "7-30 days" -> "৭-৩০ দিন"
        "30+ days" -> "৩০+ দিন"; else -> bracket
    } else bracket
    fun lowStockLabel(count: Int) = if (bn) "$count টি পণ্যের স্টক কম!" else "$count products low on stock!"
    fun productRef(id: Long) = if (bn) "পণ্য #$id" else "Product #$id"
    fun remainingStock(stock: Int) = if (bn) "বাকি: $stock" else "Remaining: $stock"
    fun slowMoverItem(nameBn: String, nameEn: String, stock: Int) = if (bn) "• $nameBn (স্টক: $stock)" else "• $nameEn (Stock: $stock)"
    fun customerDeleteDue(amount: String) = if (bn) "এই গ্রাহকের $amount বাকি আছে। আগে পেমেন্ট নিন।" else "This customer has $amount due. Please receive payment first."
    fun confirmDeleteCustomer(name: String) = if (bn) "আপনি কি $name কে মুছে ফেলতে চান?" else "Are you sure you want to delete $name?"
    fun productDeleted(name: String) = if (bn) "$name মুছে ফেলা হয়েছে" else "$name deleted"
    fun confirmDeleteProduct(name: String) = if (bn) "$name মুছে ফেলবেন? এই পণ্যের সকল তথ্য হারিয়ে যাবে।" else "Delete $name? All product data will be lost."
    fun stockChangeTitle(name: String, isIn: Boolean) = if (bn) "${if (isIn) "স্টক ইন" else "স্টক আউট"} - $name" else "${if (isIn) "Stock In" else "Stock Out"} - $name"
    fun transactionHistoryTitle(name: String) = if (bn) "লেনদেন ইতিহাস - $name" else "Transaction History - $name"
    fun unitText(unit: String): String = if (bn) when (unit) {
        "kg" -> "কেজি"; "pcs" -> "পিস"; "ltr" -> "লিটার"
        "mon" -> "মণ"; "dozen" -> "ডজন"; "g" -> "গ্রাম"
        "ton" -> "টন"; else -> unit
    } else when (unit) {
        "kg" -> "kg"; "pcs" -> "pcs"; "ltr" -> "L"
        "mon" -> "mon"; "dozen" -> "dozen"; "g" -> "g"
        "ton" -> "ton"; else -> unit
    }
    fun avgSaleValue(formatted: String) = if (bn) "গড় $formatted" else "Avg $formatted"
    fun dateFormatPattern() = if (bn) "EEEE, dd MMMM yyyy" else "EEEE, MMMM dd, yyyy"
}
